// Available Keywords related to tech field copied from ChatGpt
let availableKeywords = [
    'Vivek Mangal',
    'HTML',
    'CSS',
    'JavaScript',
    'React',
    'Angular',
    'Vue.js',
    'Node.js',
    'Python',
    'Java',
    'C++',
    'C#',
    'PHP',
    'Ruby',
    'Swift',
    'Android',
    'iOS',
    'Git',
    'GitHub',
    'Docker',
    'Kubernetes',
    'SQL',
    'MongoDB',
    'Firebase',
    'REST API',
    'GraphQL',
    'Responsive Design',
    'UI/UX',
    'Frontend',
    'Backend',
    'Full Stack',
    'DevOps',
    'Machine Learning',
    'Artificial Intelligence',
    'Cybersecurity',
    'Blockchain',
    'Cloud Computing',
    'Big Data',
    'IoT',
    'AR/VR',
    'Unity',
    'Game Development',
    'Networking',
    'Linux',
    'Windows',
    'macOS',
    'Shell Scripting',
    'Bash',
    'Automation',
    'Testing',
    'Agile',
    'Scrum',
    'Kanban',
    'Continuous Integration',
    'Continuous Deployment',
    'Microservices',
    'Web Development',
    'Mobile Development',
    'Data Science',
    'Data Analysis',
    'Algorithms',
    'Data Structures',
    'Software Architecture',
    'Programming',
    'Code Review',
    'Version Control',
    'Bug Tracking',
    'Code Quality',
    'Technical Documentation',
    'API',
    'SSL',
    'TLS',
    'OAuth',
    'JSON',
    'XML',
    'WebSocket',
    'Containerization',
    'Jenkins',
    'Travis CI',
    'JIRA',
    'Confluence',
    'Slack',
    'Microsoft Teams',
    'Visual Studio Code',
    'Sublime Text',
    'Eclipse',
    'IntelliJ IDEA',
    'VS Studio',
    'Atom',
    'WebStorm',
    'PyCharm',
    'NetBeans',
    'Brackets',
    'Notepad++',
    'Emacs',
    'Vim',
    'Stack Overflow',
    'Tech Stack',
    'Code Snippet',
    'Algorithm Complexity',
    'API Gateway',
    'Load Balancing',
    'Monitoring',
    'Logging',
    'Error Handling',
    'Security Best Practices',
    'Performance Optimization',
    'Dependency Injection',
    'Scalability',
    'Cross-platform Development',
    'Code Versioning',
    'Code Collaboration',
    'Unit Testing',
    'Integration Testing',
    'End-to-End Testing',
    'Security Testing',
    'Code Analysis',
    'Code Optimization',
    'Design Patterns',
    'Software Development Life Cycle',
    'Version Control System',
    'Code Repository',
    'Codebase',
    'Codebase Management',
    'Code Review Process',
    'Continuous Monitoring',
    'Incident Response',
    'Root Cause Analysis',
    'Technical Debt',
    'Refactoring',
    'Code Deployment',
    'Container Orchestration',
    'Serverless Architecture',
    'Micro Frontends',
    'Progressive Web Apps',
    'Single Page Applications',
    'WebAssembly',
    'Responsive Web Design',
    'Web Accessibility',
    'User Interface Design',
    'User Experience Design',
    'User Research',
    'Wireframing',
    'Prototyping',
    'Mobile User Interface Design',
    'Mobile User Experience Design',
    'Responsive Design',
    'Design Thinking',
    'Product Design',
    'Design System',
    'UI Framework',
    'UI Components',
    'UI Library',
    'UI Kit',
    'Design Tokens',
    'Atomic Design',
    'Design Patterns',
    'Figma',
    'Sketch',
    'Adobe XD',
    'InVision',
    'Zeplin',
    'Abstract',
    'Proto.io',
    'Axure RP',
    'Balsamiq',
    'Moqups',
    'Whimsical',
    'Marvel',
    'Principle',
    'Flinto',
    'Origami Studio',
    'Craft',
    'User Flow',
    'Information Architecture',
    'Card Sorting',
    'Usability Testing',
    'A/B Testing',
    'Conversion Rate Optimization',
    'Color Theory',
    'Typography',
    'Visual Hierarchy',
    'Grid Systems',
    'Responsive Typography',
    'Iconography',
    'Logo Design',
    'Illustration',
    'Photography',
    'Motion Design',
    'Video Editing',
    'Game Design',
    'Virtual Reality Design',
    'Augmented Reality Design',
    'Voice User Interface Design',
    'Chatbot Design',
    'Accessibility',
    'Inclusive Design',
    'Design Ethics',
    'User-Centered Design',
    'Persona',
    'User Stories',
    'User Journey',
    'User Persona',
    'Wireframe',
    'Prototype',
    'Mockup',
    'High-Fidelity Prototype',
    'Low-Fidelity Prototype',
    'Design Handoff',
    'Design Collaboration',
    'Design System Documentation',
    'UI Testing',
    'Accessibility Testing',
    'Cross-Browser Testing',
    'Performance Testing',
    'Usability Testing',
    'User Testing',
    'User Research',
    'Heuristic Evaluation',
    'Design Review',
    'Design Critique',
    'Design Sprint',
    'Product Management',
    'Product Owner',
    'Product Manager',
    'Product Backlog',
    'Product Roadmap',
    'Minimum Viable Product (MVP)',
    'User Story',
    'Agile Development',
    'Scrum Master',
    'Sprint Planning',
    'Sprint Review',
    'Sprint Retrospective',
    'Backlog Grooming',
    'Daily Standup',
    'Burn Down Chart',
    'Velocity',
    'Release Planning',
    'Product Strategy',
    'Market Research',
    'Competitor Analysis',
    'SWOT Analysis',
    'Value Proposition',
    'Business Model Canvas',
    'Lean Startup',
    'Design Thinking',
    'Customer Development',
    'Product-Market Fit',
    'User Acquisition',
    'User Retention',
    'Customer Feedback',
    'Customer Support',
    'Net Promoter Score (NPS)',
    'Churn Rate',
    'Lifetime Value (LTV)',
    'Customer Journey Mapping',
    'Customer Persona',
    'Customer Segmentation',
    'Customer Satisfaction (CSAT)',
    'Customer Success',
    'Customer Advocacy',
    'Customer Onboarding',
    'Customer Churn',
    'Customer Experience (CX)',
    'User Engagement',
    'User Onboarding',
    'User Retention',
    'User Churn',
    'User Experience Metrics',
    'User Engagement Metrics',
    'Key Performance Indicators (KPIs)',
    'Data Analytics',
    'Data-driven Decision Making',
    'Business Intelligence',
    'Data Visualization',
    'Data Analysis Tools',
    'Data Science',
    'Data Engineering',
    'Data Warehousing',
    'Data Mining',
    'Machine Learning',
    'Predictive Analytics',
    'Big'
];
// Code
const resultBox = document.querySelector(".result-box");
const inputBox = document.getElementById("input-box");

//Function to check
inputBox.onkeyup = function() {
    let result = [];
    let input = inputBox.value;
    if(input.length){
        result = availableKeywords.filter((keyword) => {
          return  keyword.toLowerCase().includes(input.toLowerCase());
        });
        console.log(result);
    }
    display(result);
    if(!result.length)
    {
        resultBox.innerHTML = '';
    }
}
//Function to display
function display(result){
    const content = result.map((list)=>{
       return "<li onclick=selectInput(this)>" + list + "</li>" ;
    });
    resultBox.innerHTML = "<ul>" + content.join('') + "</ul>";
}

function selectInput(list) {
    inputBox.value = list.innerHTML;
    resultBox.innerHTML = '';
}